#Array of string values in PowerShell
$apps=@(   
    #Commented out apps won't be removed!
    #"Microsoft.BioEnrollment" //Windows Hello
    #"Microsoft.MSPaint"
    #"Microsoft.Office.OneNote"
    #"Microsoft.DesktopAppInstaller"
    #"Microsoft.Microsoft3DViewer"
    #"Microsoft.WindowsCalculator"
    #"Microsoft.WindowsCamera"
    #"Microsoft.WindowsStore"
    "9E2F88E3.Twitter"
    "ClearChannelRadioDigital.iHeartRadio"
    "Flipboard.Flipboard"
    "king.com.CandyCrushSodaSaga"
    "Microsoft.3DBuilder"
    "Microsoft.Appconnector"
    "Microsoft.Advertising.Xaml"
    "Microsoft.BingFinance"
    "Microsoft.BingNews"
    "Microsoft.BingSports"
    "Microsoft.BingWeather"
    "Microsoft.BingTravel"
    "Microsoft.BingHealthAndFitness"
    "Microsoft.BingFoodAndDrink"
    "Microsoft.BingFinance"
    "Microsoft.CommsPhone"
    "microsoft.windowscommunicationsapps"
    "Microsoft.Getstarted"
    "Microsoft.GetHelp"
    "Microsoft.Messaging"
    "Microsoft.MicrosoftOfficeHub"
    "Microsoft.MicrosoftSolitaireCollection"
    "Microsoft.MicrosoftStickyNotes"
    "Microsoft.MixedReality.Portal"
    "Microsoft.Office.Sway"
    "Microsoft.OneConnect"
    "Microsoft.People"
    "Microsoft.Print3D"
    "Microsoft.SkypeApp"
    "Microsoft.ScreenSketch"
    "Microsoft.Wallet"
    "Microsoft.Windows.Phone"
    "Microsoft.Windows.Photos"
    "Microsoft.WindowsAlarms"
    "Microsoft.WindowsFeedbackHub"
    "Microsoft.WindowsFeedback"
    "Microsoft.WindowsMaps"
    "Microsoft.WindowsPhone"
    "Microsoft.WindowsSoundRecorder"
    "Microsoft.Xbox.TCUI"
    "Microsoft.XboxApp"
    "Microsoft.XboxGameOverlay"
    "Microsoft.XboxGamingOverlay"
    "Microsoft.XboxIdentityProvider"
    "Microsoft.XboxSpeechToTextOverlay"
    "Microsoft.ZuneMusic"
    "Microsoft.ZuneVideo"
    "Microsoft.YourPhone"
    "microsoft.windowscommunicationsapps"
    "Microsoft.MinecraftUWP"
    "ShazamEntertainmentLtd.Shazam"  
    "Microsoft.Windows.PeopleExperienceHost"
    "Microsoft.Windows.ParentalControls"
    "Microsoft.XboxGameCallableUI"
    "4DF9E0F8.Netflix"
	"king.com.CandyCrushFriends"
	"Microsoft.BingTranslator"
	"NORDCURRENT.COOKINGFEVER"
	"ThumbmunkeysLtd.PhototasticCollage"
	"7EE7776C.LinkedInforWindows"
	"Fitbit.FitbitCoach"
	"Microsoft.FreshPaint"
	"64885BlueEdge.OneCalendar"
	"61908RichardWalters.Calculator"
	"21090PaddyXu.QuickLook"
	"49297T.Partl.ClockOut"
)
 
foreach ($app in $apps) {    
    Get-AppxPackage -Name $app | Remove-AppxPackage -AllUsers
    Get-AppXProvisionedPackage -Online | where DisplayName -EQ $app | Remove-AppxProvisionedPackage -Online
 
    $appPath="$Env:LOCALAPPDATA\Packages\$app*"
    Remove-Item $appPath -Recurse -Force -ErrorAction 0
}
